# @Generated by find_versions.py. DO NOT EDIT.
from __future__ import annotations

import json
import os
from functools import lru_cache
from importlib import resources
from typing import TypedDict, cast

from ._utils import PythonVersion

BASE_URL_ENV_VAR = "PBS_INSTALLER_BASE_URL"


class PythonVersionPayload(TypedDict):
    implementation: str
    major: int
    minor: int
    micro: int
    freethreaded: bool


class PythonFilePayload(TypedDict):
    platform: str
    arch: str
    install_only: bool
    filename: str
    url: str
    sha256: str | None


class VersionPayload(TypedDict):
    python_version: PythonVersionPayload
    files: list[PythonFilePayload]


PythonVersionIndex = dict[PythonVersion, dict[tuple[str, str, bool], tuple[str, str | None]]]


def _normalize_base_url(base_url: str | None) -> str | None:
    if base_url is None:
        return None
    normalized = base_url.rstrip("/")
    return normalized or None


@lru_cache(maxsize=1)
def _read_versions_payload() -> list[VersionPayload]:
    package = __package__ or "pbs_installer"
    with resources.open_text(package, "versions.json", encoding="utf-8") as fp:
        return cast(list[VersionPayload], json.load(fp))


def _build_url(url: str, filename: str, base_url: str | None) -> str:
    if base_url is None:
        return url
    return f"{base_url}/{filename}"


@lru_cache(maxsize=None)
def get_python_versions(base_url: str | None = None) -> PythonVersionIndex:
    resolved_base_url = _normalize_base_url(base_url)
    versions: PythonVersionIndex = {}
    for payload in _read_versions_payload():
        version_data = payload["python_version"]
        version = PythonVersion(
            version_data["implementation"],
            version_data["major"],
            version_data["minor"],
            version_data["micro"],
            version_data["freethreaded"],
        )
        files: dict[tuple[str, str, bool], tuple[str, str | None]] = {}
        for file_data in payload["files"]:
            files[(file_data["platform"], file_data["arch"], file_data["install_only"])] = (
                _build_url(file_data["url"], file_data["filename"], resolved_base_url),
                file_data["sha256"],
            )
        versions[version] = files
    return versions


PYTHON_VERSIONS = get_python_versions(os.getenv(BASE_URL_ENV_VAR))
